import type { Ticket } from "./types";

export const tickets: Ticket[] = [
  {
    id: "CD-1042",
    subject: "Erro ao exportar relatório mensal",
    client: "Contas & Gestão",
    contact: "Rui Abreu",
    status: "triage",
    priority: "high",
    owner: "Roberto",
    channel: "Portal",
    service: "Dashboard BI",
    createdAt: "2026-05-26 09:14",
    updatedAt: "2026-05-27 10:22",
    firstResponseMinutes: 34,
    description:
      "O relatório financeiro de abril exporta sem a coluna de margem quando o filtro por categoria está ativo.",
    attachments: ["print-relatorio-abril.png", "export-abril.csv"],
    messages: [
      {
        author: "Rui Abreu",
        role: "client",
        time: "Ontem, 09:14",
        body: "Ao exportar o relatório mensal, a margem desaparece quando filtro por categoria.",
      },
      {
        author: "Roberto",
        role: "team",
        time: "Ontem, 09:48",
        body: "Obrigado pelo detalhe. Já reproduzimos o comportamento e estamos a rever o exportador.",
      },
    ],
    internalNotes: [
      "Validar serialização do campo marginRate no export CSV.",
      "Cliente usa relatório em reunião semanal de gestão.",
    ],
  },
  {
    id: "CD-1041",
    subject: "Novo utilizador sem acesso ao portal",
    client: "Clínica Atlântico",
    contact: "Marta Nunes",
    status: "waiting",
    priority: "normal",
    owner: "Inês",
    channel: "Email",
    service: "Portal cliente",
    createdAt: "2026-05-25 15:41",
    updatedAt: "2026-05-27 09:10",
    firstResponseMinutes: 52,
    description:
      "A rececionista nova recebeu convite, mas não consegue concluir o primeiro login.",
    attachments: ["erro-login.png"],
    messages: [
      {
        author: "Marta Nunes",
        role: "client",
        time: "Segunda, 15:41",
        body: "A nova utilizadora fica presa no ecrã de convite expirado.",
      },
      {
        author: "Inês",
        role: "team",
        time: "Segunda, 16:33",
        body: "Enviei novo convite. Podem confirmar se chegou à caixa de entrada?",
      },
    ],
    internalNotes: ["Aguardar confirmação do cliente."],
  },
  {
    id: "CD-1040",
    subject: "Pedido de alteração ao formulário de reservas",
    client: "Vila Verde Tours",
    contact: "Miguel Sousa",
    status: "new",
    priority: "normal",
    owner: "Sem dono",
    channel: "WhatsApp",
    service: "Sistema de reservas",
    createdAt: "2026-05-27 11:05",
    updatedAt: "2026-05-27 11:05",
    firstResponseMinutes: 0,
    description:
      "Cliente pretende adicionar campo obrigatório para número de participantes por reserva.",
    attachments: [],
    messages: [
      {
        author: "Miguel Sousa",
        role: "client",
        time: "Hoje, 11:05",
        body: "Precisamos de recolher o número de participantes antes do pagamento.",
      },
    ],
    internalNotes: ["Avaliar impacto no checkout e nos emails automáticos."],
  },
  {
    id: "CD-1039",
    subject: "Integração ERP com falhas intermitentes",
    client: "Solar Norte",
    contact: "Carla Mateus",
    status: "triage",
    priority: "urgent",
    owner: "Roberto",
    channel: "Telefone",
    service: "Integrações",
    createdAt: "2026-05-27 08:30",
    updatedAt: "2026-05-27 10:55",
    firstResponseMinutes: 12,
    description:
      "A sincronização de encomendas com o ERP falhou três vezes durante a manhã.",
    attachments: ["erp-log-2026-05-27.txt"],
    messages: [
      {
        author: "Carla Mateus",
        role: "client",
        time: "Hoje, 08:30",
        body: "Temos encomendas que não aparecem no ERP desde as 07:50.",
      },
      {
        author: "Roberto",
        role: "team",
        time: "Hoje, 08:42",
        body: "Estamos a analisar os logs e pausámos novas sincronizações automáticas.",
      },
    ],
    internalNotes: [
      "Provável timeout no endpoint do ERP.",
      "Preparar retry manual para encomendas pendentes.",
    ],
  },
  {
    id: "CD-1038",
    subject: "Fecho de ticket após validação",
    client: "Madeira Homes",
    contact: "Tiago Sá",
    status: "resolved",
    priority: "low",
    owner: "Inês",
    channel: "Portal",
    service: "CRM imobiliário",
    createdAt: "2026-05-21 14:10",
    updatedAt: "2026-05-24 17:18",
    firstResponseMinutes: 44,
    description:
      "A equipa pediu alteração visual no detalhe de imóvel. Cliente validou em produção.",
    attachments: ["antes-depois.png"],
    messages: [
      {
        author: "Tiago Sá",
        role: "client",
        time: "21 Mai, 14:10",
        body: "Podem destacar melhor a etiqueta de imóvel reservado?",
      },
      {
        author: "Inês",
        role: "team",
        time: "24 Mai, 17:18",
        body: "Alteração publicada e validada. Vamos fechar o pedido.",
      },
    ],
    internalNotes: ["Boa melhoria para aplicar noutras contas imobiliárias."],
  },
  {
    id: "CD-1037",
    subject: "Dúvida sobre permissões de equipa",
    client: "FormaPro Academy",
    contact: "Sofia Lima",
    status: "waiting",
    priority: "normal",
    owner: "Roberto",
    channel: "Email",
    service: "Área de aluno",
    createdAt: "2026-05-23 10:02",
    updatedAt: "2026-05-26 12:35",
    firstResponseMinutes: 67,
    description:
      "Cliente quer separar permissões entre coordenadores, formadores e financeiro.",
    attachments: ["mapa-permissoes.xlsx"],
    messages: [
      {
        author: "Sofia Lima",
        role: "client",
        time: "23 Mai, 10:02",
        body: "Enviámos um mapa com as permissões esperadas por perfil.",
      },
      {
        author: "Roberto",
        role: "team",
        time: "23 Mai, 11:09",
        body: "Recebido. Vamos devolver proposta de perfis até amanhã.",
      },
    ],
    internalNotes: ["Transformar pedido em melhoria de produto."],
  },
];
